### ISSUE TITLE
Example doesn't work!

### ISSUE THREAD

**Issue by periloso** [andreausu/CodiceFiscale#8]
I've tried the example code as written in the README, but it doesn't work.
Here's the problem: the code written is
`$calc->('Nome', 'Cognome', 'M', new \DateTime('1992-03-06') 'F205');`

but should be instead:
`$calc->calcola('Nome', 'Cognome', 'M', new \DateTime('1992-03-06'), 'F205');`

The function name "calcola" is missing, and there isn't a comma "," before 'F205'.
Except that, it seems to magically work... thanks! :)

**Comment by andreausu** [comment]
Fixed, thanks :)
